迁移Kawa-ui组件库至新架构
kawa-fe/kawa-resume pull request #27
Opened 2024-12-13 03:35 UTC by Shabi-x

- 搭建kawa-ui大仓基本结构(目前还是基于vite搭建

- 初步迁移两个简单组件（抽象性后续有提升空间）
![image](https://github.com/user-attachments/assets/2f396227-5b0b-43e0-a0bf-fe44e9d5eae9)
![image](https://github.com/user-attachments/assets/e0fcafb7-0eb6-465b-8648-71a01ab6fa19)

**- 搭建storybook测试UI组件流程** :
- cd packages/kawa-ui
- pnpm storybook

2024-12-16 08:13 UTC, Shabi-x commented
> Hi @Shabi-x, 考虑修改一下你的pr标题，参考[约定式提交](https://www.conventionalcommits.org/zh-hans/v1.0.0/)规范 :D

好的

2024-12-16 08:20 UTC, fu050409 requested changes

2024-12-16 08:20 UTC, fu050409 commented on packages/kawa-ui/.storybook/main.ts
> +import type { StorybookConfig } from "@storybook/react-vite";
我们的项目是基于工作区（`workspace`）的，我们是否应该将StoryBook的配置归置于根目录呢（由于我未使用过此项目，请自行决断）？同时，@LofiSu 已经合入了`components`的拉取请求，考虑使用`@kawafe/components`？

同时，事实上我建议将StoryBook环境配置与此PR拆分开来，它们实际上完成了两个任务:D

2024-12-16 08:20 UTC, fu050409 commented on packages/kawa-ui/src/skillList/index.scss
> +.con {
我们项目会配置`tailwindcss`（在接下来的PR中），考虑将基础CSS迁移到`tailwindcss`，注意我们不应该写入任何与样式有关的`class`，因为我们的className应该来自于`@kawafe/theme`。

2024-12-16 08:20 UTC, fu050409 commented on packages/kawa-ui/src/skillList/index.tsx
> +        相关技能
考虑在`@kawafe/core`中，在`userData`加入此文本的选项，或者我们可以考虑迁移到`i18n`并允许用户定制此处应当显示的文本。

2024-12-16 08:48 UTC, closed without merging

2024-12-16 08:58 UTC, Shabi-x commented on packages/kawa-ui/src/skillList/story/skillList.stories.tsx
> +export const ShabixExample: Story = {
感谢提醒

2024-12-19 02:27 UTC, Shabi-x commented on packages/kawa-ui/src/skillList/index.scss
> +.con {
我想知道，component里不需要写样式，这里的样式包括布局的css吗