feat(List): 开发通用列表式数据渲染组件
kawa-fe/kawa-resume pull request #32
Opened 2024-12-19 03:40 UTC by Shabi-x

* List组件可以用于简历中的项目经历、技能清单、工作经历......等等可能的列表式数据的渲染
 * 暂时开发了两个列表样式，后续可以在/packages/components/list/listrenderitem中继续开发不同渲染形式的ListRenderItem

![7fc5290e0afcac0a2e0a2c233dd8ff62](https://github.com/user-attachments/assets/a6ac4717-a9a2-4857-b323-c19dcd81d6a6)
![222a2f718f779591540659a1fa5bd2b0](https://github.com/user-attachments/assets/49134d40-2c2a-43a3-89c7-609227929124)

2024-12-19 06:36 UTC, LofiSu commented
goooooooood！加油！做好了开组会分享！

2024-12-20 08:52 UTC, fu050409 requested changes

2024-12-20 08:52 UTC, fu050409 commented on package.json
> +    "storybook": "cd packages/components && pnpm storybook"
考虑使用`pnpm --filter`来替代？

2024-12-20 08:52 UTC, fu050409 commented on packages/components/image/Image.types.ts
> +import React from "react";
考虑使用`type React`, `React`导入仅用于类型注解，加入`type`语法以便编译器优化。

2024-12-20 08:58 UTC, Shabi-x commented on package.json
> +    "storybook": "cd packages/components && pnpm storybook"
很好的建议，学到啦，感谢！

2024-12-20 08:59 UTC, Shabi-x commented on packages/components/image/Image.types.ts
> +import React from "react";
好的之前没有注意过这个细节，感谢！

2024-12-20 09:05 UTC, fu050409 commented on packages/components/list/ListRenderitem/index.style.ts
> +export const ListItemStyle: React.CSSProperties = {
我们将会使用`tailwindcss`来替代`style`，你希望先合并此分支还是在tailwind环境配置完成后，再直接对此分支进行修改？

2024-12-20 09:06 UTC, Shabi-x commented on packages/components/list/ListRenderitem/index.style.ts
> +export const ListItemStyle: React.CSSProperties = {
先合并吧，后续迁一下tailwind

2024-12-23 07:44 UTC, fu050409 commented
我稍后会合入tailwindcss和配置，随后会给出实际的用例😊

2024-12-23 08:35 UTC, LofiSu commented
> 又完成了一个简历头的物料组件（简单的一种），但是目前还不知道怎么抽离样式到theme中，需要后续统一迁移 @LofiSu @fu050409
> 
> ![image](https://private-user-images.githubusercontent.com/131671885/398072746-4b492232-4d5e-4efe-93b7-7f2fd5223b4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDMwNzAsIm5iZiI6MTczNDk0Mjc3MCwicGF0aCI6Ii8xMzE2NzE4ODUvMzk4MDcyNzQ2LTRiNDkyMjMyLTRkNWUtNGVmZS05M2I3LTdmMmZkNTIyM2I0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwODMyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjBlZmY2NjVhYjg1ZDNhZTRjNDdmNzYwN2YyY2YwNDU1MmIxYjJiMjg3MGExOGVhZWEzYmE1OGY5ZjBiMzU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6gW7log64FGHnv5hpDDeXOvC2rQlPMGO1TIkMB7LqVU)

先放到components包里面，样式我们可以参考一下这个https://cv.talencat.com/zh

2024-12-23 08:57 UTC, LofiSu approved these changes
lgtm

2025-01-13 05:09 UTC, fu050409 commented
@Shabi-x Take a look about bot's review? Also, consider refactor your codes to use tailwindcss instead? Otherwise, Idk how does storybook works, we may need to integrate it with tailwind.

2025-01-13 05:20 UTC, Shabi-x commented
> @Shabi-x Take a look about bot's review? Also, consider refactor your codes to use tailwindcss instead? Otherwise, Idk how does storybook works, we may need to integrate it with tailwind.

ok

2025-01-13 07:59 UTC, Shabi-x commented
@fu050409 已经迁移至tailwindcss了

2025-01-13 08:02 UTC, fu050409 commented on packages/components/package.json
> +    "watch:css": "tailwindcss -i ./index.css -o ./dist/tailwind.css --watch"
It's useless, farm can automatically handle tailwindcss and vite can do this too.

2025-01-13 08:07 UTC, fu050409 commented on packages/components/tailwind.config.js
> +    "./**/*.{js,ts,jsx,tsx}",
It's odd since this line covered all files

2025-01-13 08:07 UTC, fu050409 commented on packages/components/tailwind.config.js
> +    "!**/node_modules/**" // 排除 node_modules 目录
It's unreasonable to exclude node modules dir since we will never change it so the hmr never be trigered.

2025-01-13 08:07 UTC, fu050409 commented on packages/components/stories/list.stories.tsx
> +export const PointedList: StoryFn = () => (
What's the difference between they two?

2025-01-22 10:11 UTC, Shabi-x commented on packages/components/tailwind.config.js
这里的content配置不确定应该怎么做

2025-01-22 10:36 UTC, fu050409 commented on packages/components/stories/list.stories.tsx
> +export const PointedList: StoryFn = () => (
@Shabi-x I think you can just leave a flag to create a single component contains 2 lists but not separate them. We must keep our codes clean and simple.

2025-01-22 10:38 UTC, fu050409 commented on packages/components/tailwind.config.js
暂时先这样就可以，我稍后处理这部分内容

2025-01-22 10:38 UTC, fu050409 requested changes

2025-01-22 10:38 UTC, fu050409 commented on pnpm-lock.yaml
Consider update your local nodejs versions? We are using pnpm@latest now

2025-01-22 10:39 UTC, fu050409 commented on packages/components/list/list.tsx
> +      </div>
@Shabi-x take a look?

2025-01-22 15:52 UTC, LofiSu commented
这个兔子引入真的有帮助吗，我看的眼花缭乱的

2025-01-22 15:54 UTC, fu050409 commented
> 这个兔子引入真的有帮助吗，我看的眼花缭乱的

总的来说它的建议符合原生HTML5的一些规范

2025-01-22 15:58 UTC, LofiSu commented
> > 这个兔子引入真的有帮助吗，我看的眼花缭乱的
> 
> 总的来说它的建议符合原生HTML5的一些规范

@Shabi-x 要不要拆解一点，一个组件一个组件推上来？这个卡了好久了，还是说因为cli没做好 @fu050409 🆒

2025-01-22 16:02 UTC, fu050409 commented
> > > 这个兔子引入真的有帮助吗，我看的眼花缭乱的
> > 
> > 总的来说它的建议符合原生HTML5的一些规范
> 
> @Shabi-x 要不要拆解一点，一个组件一个组件推上来？这个卡了好久了，还是说因为cli没做好 @fu050409 🆒

cli部分是用来简化开发流程的，不会影响直接的PR审计合入

2025-01-23 04:01 UTC, Shabi-x commented on packages/components/tailwind.config.js
因为Tailwind CSS 的 PurgeCSS 默认只保留静态分析中找到的类名，动态类名生成（如 `text-${color}`）会被 PurgeCSS 移除。
这里用taillwindcss提供的safelist 来解决动态类名问题

2025-01-23 04:34 UTC, fu050409 commented on packages/components/tailwind.config.js
为什么要使用PurgeCSS？

2025-01-23 04:36 UTC, fu050409 commented on packages/components/color_theme_config.ts
> +};
Please write doc string in English

2025-01-23 04:37 UTC, Shabi-x commented on packages/components/color_theme_config.ts
> +};
> @Shabi-x Please write doc string in English
👌🏻

2025-01-23 05:10 UTC, fu050409 commented on packages/components/color_theme_config.ts
后面会使用theme lib

2025-01-23 05:10 UTC, fu050409 commented on packages/components/color_theme_config.ts
后面会使用theme lib

2025-01-24 04:27 UTC, fu050409 requested changes

2025-01-24 04:27 UTC, fu050409 commented on packages/components/package.json
> +    "vite": "^6.0.7"
why?

2025-01-24 04:27 UTC, fu050409 commented on packages/components/resume_header/index.ts
why create an empty file?

2025-01-24 04:40 UTC, Shabi-x commented on packages/components/package.json
> +    "vite": "^6.0.7"
已经移除vite和autofixer了

2025-01-24 04:41 UTC, Shabi-x commented on packages/components/resume_header/index.ts
已修正

2025-01-24 04:42 UTC, fu050409 approved these changes

2025-01-24 06:17 UTC, merged